# fly.toml file generated for khamlaungportfolio on 2023-03-22T12:00:30+06:30

app = "khamlaungportfolio"
primary_region = "sin"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"